name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  maven:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and verify
      run: ./mvnw clean package verify

    - name: Upload artifact for Docker job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path:
          '${{ github.workspace }}/target/*.jar'

  docker:
  
    runs-on: ubuntu-latest
    needs: maven
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    - name: Download artifact from Maven job
      uses: actions/download-artifact@v3
      with:
        name: java-app

    - name: Login with Github Container registry
      run: docker login ghcr.io -u Attilae -p ${{ github.token }}

    - name: Build the Docker image
      run: docker build . -t ghcr.io/attilae/cubix/1/optional/app:springboot
    
    - name: Push to Docker
      run: docker push ghcr.io/attilae/cubix/1/optional/app:springboot
